#!/bin/bash

domain=$1
host=$2
APIKey="YOUR_API_KEY_FROM_GODADDY"
APISecret="YOUR_SECRET_API_KEY_FROM_GODADDY"
WanIP=`curl -s https://api.ipify.org` #Check my IP Address
GDIP=`curl -s -X GET -H "Authorization: sso-key ${APIKey}:${APISecret}" "https://api.godaddy.com/v1/domains/${domain}/records/A/${host}" | cut -d '[' -f 2 | cut -d ']' -f 1 | jq -r '.data'`
if [ "$WanIP" != "$GDIP" -a "$WanIP" != "" ]; then
	curl -s -X PUT "https://api.godaddy.com/v1/domains/${domain}/records/A/${host}" -H "Authorization: sso-key ${APIKey}:${APISecret}" -H "Content-Type: application/json" -d "[{\"data\": \"${WanIP}\"}]"
fi
